Debug postgis failure

diff --git a/.github/workflows/tests.yaml b/.github/workflows/tests.yaml
--- a/.github/workflows/tests.yaml
+++ b/.github/workflows/tests.yaml
@@ -35,35 +35,35 @@ jobs:
         postgis: [false]
         dev: [false]
         env:
-          - ci/envs/38-minimal.yaml
-          - ci/envs/39-no-optional-deps.yaml
-          - ci/envs/38-pd12-defaults.yaml
-          - ci/envs/38-latest-defaults.yaml
-          - ci/envs/38-latest-conda-forge.yaml
+          # - ci/envs/38-minimal.yaml
+          # - ci/envs/39-no-optional-deps.yaml
+          # - ci/envs/38-pd12-defaults.yaml
+          # - ci/envs/38-latest-defaults.yaml
+          # - ci/envs/38-latest-conda-forge.yaml
           - ci/envs/39-pd13-conda-forge.yaml
-          - ci/envs/39-latest-conda-forge.yaml
-          - ci/envs/310-latest-conda-forge.yaml
+          # - ci/envs/39-latest-conda-forge.yaml
+          # - ci/envs/310-latest-conda-forge.yaml
           - ci/envs/311-latest-conda-forge.yaml
-        include:
-          - env: ci/envs/38-latest-conda-forge.yaml
-            os: macos-latest
-            postgis: false
-            dev: false
-          - env: ci/envs/39-latest-conda-forge.yaml
-            os: macos-latest
-            postgis: false
-            dev: false
-          - env: ci/envs/38-latest-conda-forge.yaml
-            os: windows-latest
-            postgis: false
-            dev: false
-          - env: ci/envs/39-latest-conda-forge.yaml
-            os: windows-latest
-            postgis: false
-            dev: false
-          - env: ci/envs/310-dev.yaml
-            os: ubuntu-latest
-            dev: true
+        # include:
+        #   - env: ci/envs/38-latest-conda-forge.yaml
+        #     os: macos-latest
+        #     postgis: false
+        #     dev: false
+        #   - env: ci/envs/39-latest-conda-forge.yaml
+        #     os: macos-latest
+        #     postgis: false
+        #     dev: false
+        #   - env: ci/envs/38-latest-conda-forge.yaml
+        #     os: windows-latest
+        #     postgis: false
+        #     dev: false
+        #   - env: ci/envs/39-latest-conda-forge.yaml
+        #     os: windows-latest
+        #     postgis: false
+        #     dev: false
+        #   - env: ci/envs/310-dev.yaml
+        #     os: ubuntu-latest
+        #     dev: true
 
     steps:
       - uses: actions/checkout@v3
@@ -93,18 +93,18 @@ jobs:
             echo "HAS_PYGEOS=0" >> $GITHUB_ENV
           fi
 
-      - name: Test without PyGEOS
-        env:
-          USE_PYGEOS: 0
-        run: |
-          pytest -v -r a -n auto --color=yes --cov=geopandas --cov-append --cov-report term-missing --cov-report xml geopandas/
+      # - name: Test without PyGEOS
+      #   env:
+      #     USE_PYGEOS: 0
+      #   run: |
+      #     pytest -v -r a -n auto --color=yes --cov=geopandas --cov-append --cov-report term-missing --cov-report xml geopandas/
 
-      - name: Test with PyGEOS
-        if: env.HAS_PYGEOS == 1
-        env:
-          USE_PYGEOS: 1
-        run: |
-          pytest -v -r a -n auto --color=yes --cov=geopandas --cov-append --cov-report term-missing --cov-report xml geopandas/
+      # - name: Test with PyGEOS
+      #   if: env.HAS_PYGEOS == 1
+      #   env:
+      #     USE_PYGEOS: 1
+      #   run: |
+      #     pytest -v -r a -n auto --color=yes --cov=geopandas --cov-append --cov-report term-missing --cov-report xml geopandas/
 
       - name: Test with PostGIS
         if: (contains(matrix.env, '39-pd13-conda-forge.yaml') || contains(matrix.env, '311-latest-conda-forge.yaml')) && contains(matrix.os, 'ubuntu')
@@ -116,7 +116,7 @@ jobs:
         run: |
           conda install postgis -c conda-forge
           sh ci/scripts/setup_postgres.sh
-          pytest -v -r a --color=yes --cov=geopandas --cov-append --cov-report term-missing --cov-report xml geopandas/io/tests/test_sql.py | tee /dev/stderr | if grep SKIPPED >/dev/null;then echo "TESTS SKIPPED, FAILING" && exit 1;fi
+          pytest -v -s -r a --color=yes --cov=geopandas --cov-append --cov-report term-missing --cov-report xml geopandas/io/tests/test_sql.py | tee /dev/stderr | if grep SKIPPED >/dev/null;then echo "TESTS SKIPPED, FAILING" && exit 1;fi
 
       - name: Test docstrings
         if: contains(matrix.env, '39-pd13-conda-forge.yaml') && contains(matrix.os, 'ubuntu')
